using mitoSoft.Razor.WordClock.Contracts;
using mitoSoft.Razor.WordClock.Models;

namespace mitoSoft.Razor.WordClock.CultureMatrixes
{
    internal class LetterMatrixEN : ICultureMatrix
    {
        public IList<MatrixCell> GetCells()
        {
            return this.Cells;
        }

        public List<MatrixCell> Cells = new()
        {
            new MatrixCell(0, 0, "I"),
            new MatrixCell(0, 1, "T"),
            new MatrixCell(0, 2, "L"),
            new MatrixCell(0, 3, "I"),
            new MatrixCell(0, 4, "S"),
            new MatrixCell(0, 5, "A"),
            new MatrixCell(0, 6, "S"),
            new MatrixCell(0, 7, "A"),
            new MatrixCell(0, 8, "M"),
            new MatrixCell(0, 9, "P"),
            new MatrixCell(0, 10, "M"),
            new MatrixCell(1, 0, "A"),
            new MatrixCell(1, 1, "C"),
            new MatrixCell(1, 2, "Q"),
            new MatrixCell(1, 3, "U"),
            new MatrixCell(1, 4, "A"),
            new MatrixCell(1, 5, "R"),
            new MatrixCell(1, 6, "T"),
            new MatrixCell(1, 7, "E"),
            new MatrixCell(1, 8, "R"),
            new MatrixCell(1, 9, "D"),
            new MatrixCell(1, 10, "C"),
            new MatrixCell(2, 0, "T"),
            new MatrixCell(2, 1, "W"),
            new MatrixCell(2, 2, "E"),
            new MatrixCell(2, 3, "N"),
            new MatrixCell(2, 4, "T"),
            new MatrixCell(2, 5, "Y"),
            new MatrixCell(2, 6, "F"),
            new MatrixCell(2, 7, "I"),
            new MatrixCell(2, 8, "V"),
            new MatrixCell(2, 9, "E"),
            new MatrixCell(2, 10, "X"),
            new MatrixCell(3, 0, "H"),
            new MatrixCell(3, 1, "A"),
            new MatrixCell(3, 2, "L"),
            new MatrixCell(3, 3, "F"),
            new MatrixCell(3, 4, "S"),
            new MatrixCell(3, 5, "T"),
            new MatrixCell(3, 6, "E"),
            new MatrixCell(3, 7, "N"),
            new MatrixCell(3, 8, "F"),
            new MatrixCell(3, 9, "T"),
            new MatrixCell(3, 10, "O"),
            new MatrixCell(4, 0, "O"),
            new MatrixCell(4, 1, "A"),
            new MatrixCell(4, 2, "F"),
            new MatrixCell(4, 3, "T"),
            new MatrixCell(4, 4, "E"),
            new MatrixCell(4, 5, "R"),
            new MatrixCell(4, 6, "O"),
            new MatrixCell(4, 7, "H"),
            new MatrixCell(4, 8, "A"),
            new MatrixCell(4, 9, "L"),
            new MatrixCell(4, 10, "F"),
            new MatrixCell(5, 0, "P"),
            new MatrixCell(5, 1, "A"),
            new MatrixCell(5, 2, "S"),
            new MatrixCell(5, 3, "T"),
            new MatrixCell(5, 4, "E"),
            new MatrixCell(5, 5, "R"),
            new MatrixCell(5, 6, "U"),
            new MatrixCell(5, 7, "N"),
            new MatrixCell(5, 8, "I"),
            new MatrixCell(5, 9, "N"),
            new MatrixCell(5, 10, "E"),
            new MatrixCell(6, 0, "O"),
            new MatrixCell(6, 1, "N"),
            new MatrixCell(6, 2, "E"),
            new MatrixCell(6, 3, "S"),
            new MatrixCell(6, 4, "I"),
            new MatrixCell(6, 5, "X"),
            new MatrixCell(6, 6, "T"),
            new MatrixCell(6, 7, "H"),
            new MatrixCell(6, 8, "R"),
            new MatrixCell(6, 9, "E"),
            new MatrixCell(6, 10, "E"),
            new MatrixCell(7, 0, "F"),
            new MatrixCell(7, 1, "O"),
            new MatrixCell(7, 2, "U"),
            new MatrixCell(7, 3, "R"),
            new MatrixCell(7, 4, "F"),
            new MatrixCell(7, 5, "I"),
            new MatrixCell(7, 6, "V"),
            new MatrixCell(7, 7, "E"),
            new MatrixCell(7, 8, "T"),
            new MatrixCell(7, 9, "W"),
            new MatrixCell(7, 10, "O"),
            new MatrixCell(8, 0, "E"),
            new MatrixCell(8, 1, "I"),
            new MatrixCell(8, 2, "G"),
            new MatrixCell(8, 3, "H"),
            new MatrixCell(8, 4, "T"),
            new MatrixCell(8, 5, "E"),
            new MatrixCell(8, 6, "L"),
            new MatrixCell(8, 7, "E"),
            new MatrixCell(8, 8, "V"),
            new MatrixCell(8, 9, "E"),
            new MatrixCell(8, 10, "N"),
            new MatrixCell(9, 0, "S"),
            new MatrixCell(9, 1, "E"),
            new MatrixCell(9, 2, "V"),
            new MatrixCell(9, 3, "E"),
            new MatrixCell(9, 4, "N"),
            new MatrixCell(9, 5, "T"),
            new MatrixCell(9, 6, "W"),
            new MatrixCell(9, 7, "E"),
            new MatrixCell(9, 8, "L"),
            new MatrixCell(9, 9, "V"),
            new MatrixCell(9, 10, "E"),
            new MatrixCell(10, 0, "T"),
            new MatrixCell(10, 1, "E"),
            new MatrixCell(10, 2, "N"),
            new MatrixCell(10, 3, "S"),
            new MatrixCell(10, 4, "E"),
            new MatrixCell(10, 5, "O"),
            new MatrixCell(10, 6, "C"),
            new MatrixCell(10, 7, "L"),
            new MatrixCell(10, 8, "O"),
            new MatrixCell(10, 9, "C"),
            new MatrixCell(10, 10, "K"),
        };
    }
}