namespace mitoSoft.Razor.WordClock.Helper
{
    internal static class LetterMatrix
    {
        public static string GetLetter(int row, int col)
        {
            var cell = Cells.First(c => c.Row == row && c.Col == col);

            return cell.Letter;
        }

        public static List<MatrixCell> Cells = new()
        {
            new MatrixCell(0, 0, "E"),
            new MatrixCell(0, 1, "S"),
            new MatrixCell(0, 2, "K"),
            new MatrixCell(0, 3, "I"),
            new MatrixCell(0, 4, "S"),
            new MatrixCell(0, 5, "T"),
            new MatrixCell(0, 6, "A"),
            new MatrixCell(0, 7, "F"),
            new MatrixCell(0, 8, "Ü"),
            new MatrixCell(0, 9, "N"),
            new MatrixCell(0, 10, "F"),

            new MatrixCell(1, 0, "Z"),
            new MatrixCell(1, 1, "E"),
            new MatrixCell(1, 2, "H"),
            new MatrixCell(1, 3, "N"),
            new MatrixCell(1, 4, "Z"),
            new MatrixCell(1, 5, "W"),
            new MatrixCell(1, 6, "A"),
            new MatrixCell(1, 7, "N"),
            new MatrixCell(1, 8, "Z"),
            new MatrixCell(1, 9, "I"),
            new MatrixCell(1, 10, "G"),

            new MatrixCell(2, 0, "D"),
            new MatrixCell(2, 1, "R"),
            new MatrixCell(2, 2, "E"),
            new MatrixCell(2, 3, "I"),
            new MatrixCell(2, 4, "V"),
            new MatrixCell(2, 5, "I"),
            new MatrixCell(2, 6, "E"),
            new MatrixCell(2, 7, "R"),
            new MatrixCell(2, 8, "T"),
            new MatrixCell(2, 9, "E"),
            new MatrixCell(2, 10, "L"),

            new MatrixCell(3, 0, "V"),
            new MatrixCell(3, 1, "O"),
            new MatrixCell(3, 2, "R"),
            new MatrixCell(3, 3, "F"),
            new MatrixCell(3, 4, "U"),
            new MatrixCell(3, 5, "N"),
            new MatrixCell(3, 6, "K"),
            new MatrixCell(3, 7, "N"),
            new MatrixCell(3, 8, "A"),
            new MatrixCell(3, 9, "C"),
            new MatrixCell(3, 10, "H"),

            new MatrixCell(4, 0, "H"),
            new MatrixCell(4, 1, "A"),
            new MatrixCell(4, 2, "L"),
            new MatrixCell(4, 3, "B"),
            new MatrixCell(4, 4, "A"),
            new MatrixCell(4, 5, "E"),
            new MatrixCell(4, 6, "L"),
            new MatrixCell(4, 7, "F"),
            new MatrixCell(4, 8, "Ü"),
            new MatrixCell(4, 9, "N"),
            new MatrixCell(4, 10, "F"),

            new MatrixCell(5, 0, "E"),
            new MatrixCell(5, 1, "I"),
            new MatrixCell(5, 2, "N"),
            new MatrixCell(5, 3, "S"),
            new MatrixCell(5, 4, "X"),
            new MatrixCell(5, 5, "A"),
            new MatrixCell(5, 6, "M"),
            new MatrixCell(5, 7, "Z"),
            new MatrixCell(5, 8, "W"),
            new MatrixCell(5, 9, "E"),
            new MatrixCell(5, 10, "I"),

            new MatrixCell(6, 0, "D"),
            new MatrixCell(6, 1, "R"),
            new MatrixCell(6, 2, "E"),
            new MatrixCell(6, 3, "I"),
            new MatrixCell(6, 4, "P"),
            new MatrixCell(6, 5, "M"),
            new MatrixCell(6, 6, "J"),
            new MatrixCell(6, 7, "V"),
            new MatrixCell(6, 8, "I"),
            new MatrixCell(6, 9, "E"),
            new MatrixCell(6, 10, "R"),

            new MatrixCell(7, 0, "F"),
            new MatrixCell(7, 1, "Ü"),
            new MatrixCell(7, 2, "N"),
            new MatrixCell(7, 3, "F"),
            new MatrixCell(7, 4, "T"),
            new MatrixCell(7, 5, "D"),
            new MatrixCell(7, 6, "S"),
            new MatrixCell(7, 7, "E"),
            new MatrixCell(7, 8, "C"),
            new MatrixCell(7, 9, "H"),
            new MatrixCell(7, 10, "S"),

            new MatrixCell(8, 0, "S"),
            new MatrixCell(8, 1, "I"),
            new MatrixCell(8, 2, "E"),
            new MatrixCell(8, 3, "B"),
            new MatrixCell(8, 4, "E"),
            new MatrixCell(8, 5, "N"),
            new MatrixCell(8, 6, "L"),
            new MatrixCell(8, 7, "A"),
            new MatrixCell(8, 8, "C"),
            new MatrixCell(8, 9, "H"),
            new MatrixCell(8, 10, "T"),

            new MatrixCell(9, 0, "N"),
            new MatrixCell(9, 1, "E"),
            new MatrixCell(9, 2, "U"),
            new MatrixCell(9, 3, "N"),
            new MatrixCell(9, 4, "Z"),
            new MatrixCell(9, 5, "E"),
            new MatrixCell(9, 6, "H"),
            new MatrixCell(9, 7, "N"),
            new MatrixCell(9, 8, "E"),
            new MatrixCell(9, 9, "L"),
            new MatrixCell(9, 10, "F"),

            new MatrixCell(10, 0, "Z"),
            new MatrixCell(10, 1, "W"),
            new MatrixCell(10, 2, "Ö"),
            new MatrixCell(10, 3, "L"),
            new MatrixCell(10, 4, "F"),
            new MatrixCell(10, 5, "U"),
            new MatrixCell(10, 6, "N"),
            new MatrixCell(10, 7, "K"),
            new MatrixCell(10, 8, "U"),
            new MatrixCell(10, 9, "H"),
            new MatrixCell(10, 10, "R"),

            new MatrixCell(-1, -1, "•"),
            new MatrixCell(-2, -2, "•"),
            new MatrixCell(-3, -3, "•"),
            new MatrixCell(-4, -4, "•"),
        };
    }
}